" @mtheunissen82 vimrc

" Unleash vims power (bye bye Vi)
set nocompatible

" Includes {{{

source $VIMRUNTIME/ftplugin/man.vim

" }}}

" Plug {{{

runtime plugged/vim-plug/plug.vim
call plug#begin('~/.vim/plugged')

" Plugins {{{

Plug 'christoomey/vim-tmux-navigator'
Plug 'evidens/vim-twig'
Plug 'haya14busa/incsearch.vim'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
Plug 'keith/tmux.vim'
Plug 'kshenoy/vim-signature'
Plug 'mileszs/ack.vim'
Plug 'mtheunissen82/MyUltiSnips'
Plug 'Raimondi/delimitMate'
Plug 'scrooloose/nerdcommenter'
Plug 'scrooloose/nerdtree'
Plug 'SirVer/ultisnips'
Plug 'stephpy/vim-php-cs-fixer'
Plug 'Townk/vim-autoclose'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-pathogen'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-unimpaired'
Plug 'vim-airline/vim-airline'
Plug 'vim-scripts/matchit.zip'

" }}}

" Themes {{{

Plug 'sickill/vim-monokai'
Plug 'w0ng/vim-hybrid'

" }}}

call plug#end()

" }}}

" Colors {{{

syntax enable
set background=dark
colorscheme hybrid

" }}}

" Misc {{{

" Set internal encoding and default encoding for files to utf-8
set encoding=utf-8
setglobal fileencoding=utf-8

filetype on
filetype plugin on
filetype indent on

" Change <Leader> to space
let mapleader=","

" Decrease the timeout to wait for mappings
set timeoutlen=350

" Increase the number of history lines that are remembered
set history=1000

" Fix my frequently wrong typed Wq (etc.) when quiting vim
command! WQ wq
command! Wq wq
command! W w
command! Q q

" Add shortcut for saving readonly files
command! WW :execute ':silent w !sudo tee % > /dev/null' | :edit!

" Save all files on losing focus:
autocmd FocusLost * :wa

" Grep word under cursor recursively
map <F4> :execute "vimgrep /" . expand("<cword>") . "/j **/.*" <Bar> cw<CR

" Add highlighting of trailing whitespace
highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/
autocmd BufWinEnter * match ExtraWhitespace /\s\+$/
autocmd InsertEnter * match ExtraWhitespace /\s\+\%#\@<!$/
autocmd InsertLeave * match ExtraWhitespace /\s\+$/
autocmd BufWinLeave * call clearmatches()

" On buffer write remove trailing whitespaces
fun! <SID>StripTrailingWhitespaces()
    let l = line(".")
    let c = col(".")
    %s/\s\+$//e
    call cursor(l, c)
endfun

autocmd FileType php,javascript,twig,yml,html,xml,vim autocmd BufWritePre <buffer> :call <SID>StripTrailingWhitespaces()

command! ShowUnicode /[^\x00-\x7F]

" }}}

" UI Config {{{

" In absence of the statusline show the ruler.
" Show line and column number of the current cursor position
set ruler

" Dont wrap lines
set nowrap

" Show the current line
set cursorline

" Enable line numbering
set number

" Use relative numbering instead of absolute
set relativenumber

" Always have 5 lines above or below the cursor when scrolling
set scrolloff=5

" When minimizing a window make it as small as possible
set winminheight=0

" Always show the status line
set laststatus=2

" Fancy c(hange) visualization
set cpoptions+=$

" I want to be able to go anywhere with my cursor
set virtualedit=all

" Show current command in statusline
set showcmd

" Enable folding
set foldenable

" Enable enhance menu when autocompleting (with <Tab>) on the commandline
set wildmenu
set wildignorecase
set wildmode=list:longest

" }}}

" Buffers {{{

" Allow buffers to be hidden (unsaved) when closing a window
set hidden

" Save on buffer switch
set autowrite

" Map F5 to list and select buffers
map <F5> :buffers<CR>:buffer<Space>

" }}}

" Tabs, Spaces and Indents {{{

" Let vim help me with indenting
set smartindent

" Copy the previous indentation on autoindenting
set copyindent

" Change tabs to 4 spaces
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set smarttab

" Round shifts to the nearest shiftwidth
set shiftround

" }}}

" Search {{{

" Enable incremental searching
set incsearch

" Enable search highlighting
set hlsearch

" Dont use case-sensitive search (use smartcase when explicit case-sensitive is needed)
set ignorecase
set smartcase

" Always do global search by default
set gdefault

" By default apply 'very magic' search
" All ASCII characters except '0'-'9', 'a'-'z', 'A'-'Z' and '_' have a special meaning.
nnoremap / /\v
vnoremap / /\v

" Enable search for selection, in visual mode with //
vnoremap // y/\v<C-R>"<CR>

" }}}

" Editing {{{

" Disable Arrow keys in normal, visual and select and operator pending mode (hjkl training)
map <up> <nop>
map <down> <nop>
map <left> <nop>
map <right> <nop>

" Disable Arrow keys in insert mode (hjkl training)
imap <up> <nop>
imap <down> <nop>
imap <left> <nop>
imap <right> <nop>

" Enable hjkl navigation in insert mode
imap <C-h> <C-o>h
imap <C-j> <C-o>j
imap <C-k> <C-o>k
imap <C-l> <C-o>l

" Make horizontal movement with j and l wrap around
set whichwrap+=<,>,h,l,[,]

" Create shortcut for Esc in insert mode (`^ makes sure the cursor stays at
" the same position as before the Esc)
imap jk <Esc>
imap kj <Esc>
inoremap <Esc> <Esc>`^

" Shortcut for easy navigating to begin/end of line
map aa ^
map ;; $

" Make j/k realy move one line down/up
nnoremap j gj
nnoremap k gk

" Make Tab and Backspace in normal mode behave the same as in insert mode
nmap <Tab> i<Tab><Esc>
nmap <Bs> i<Bs><Esc>

" Make ,o and ,O in insert mode behave similar o and O in normal mode
inoremap <Leader>o <Esc>o
inoremap <Leader>O <Esc>O

" Shortcut for inserting a semicolon at the end of the line
nmap <Leader>; A;<Esc>
imap <Leader>; <Esc>A;<Esc>

" In visual mode when pasting a previous yank
" dont overwrite the unnamed register
xnoremap p pgvy

" Shortcut for editing my vimrc
nmap <leader>v :tabedit $MYVIMRC<CR>

" Source my vimrc file after saving it
autocmd bufwritepost .vimrc source $MYVIMRC

" }}}

" Theming {{{

" Show syntax highlighting groups for word under cursor
function! SynStack()
    if !exists('*synstack')
        return
    endif
    echo map(synstack(line('.'), col('.')), "synIDattr(v:val, 'name')")
endfunc

nmap <leader>x :call SynStack()<CR>

" }}}

" Windows {{{

" When using :split pop new window below and when using :vsplit insert new window right
set splitbelow
set splitright

" Enable easy hjkl window navigation in normal mode
nmap <C-h> <C-W>h
nmap <C-j> <C-W>j
nmap <C-k> <C-W>k
nmap <C-l> <C-W>l

" Window resizing with arrow keys
nmap <Up> <C-W>-
nmap <Down> <C-W>+
nmap <Left> <C-W>>
nmap <Right> <C-W><

" Enable (up/down) arrow window navigation with ALT key and make the current window
" fullscreen, minimalize the others
nmap <A-up> <C-W>k <C-W>_
nmap <A-down> <C-W>j <C-W>_

" Shorcut for making all windows equal sized
nmap <A-=> <C-W>=

" Type qq when you want to quit all open windows
cmap qq qa

" }}}

" Plugin: NERDTree {{{
map <Leader>e :NERDTreeToggle<CR>
let g:NERDTreeShowHidden=1
let g:NERDTreeWinSize=50

" Auto open NERDTree when vim is opened without any buffers (or stdin)
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif

" Close vim when NERDTree is the only window left open
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
" }}}

" Plugin: incsearch.vim {{{
map /  <Plug>(incsearch-forward)
map ?  <Plug>(incsearch-backward)
map g/ <Plug>(incsearch-stay)

" :h g:incsearch#auto_nohlsearch
" set hlsearch (already set above)
let g:incsearch#auto_nohlsearch = 1
let g:incsearch#magic = '\v'
map n  <Plug>(incsearch-nohl-n)
map N  <Plug>(incsearch-nohl-N)
map *  <Plug>(incsearch-nohl-*)
map #  <Plug>(incsearch-nohl-#)
map g* <Plug>(incsearch-nohl-g*)
map g# <Plug>(incsearch-nohl-g#)
" }}}

" Plugin: FZF {{{
let $FZF_DEFAULT_COMMAND = 'ag --all-types --hidden --ignore-case -g ""'
nnoremap <silent> <C-P> :FZF -x<CR>
nmap <Leader>p :FZF -x<CR>
" }}}

" Plugin: Ack {{{
:let g:ackprg = 'ag --all-types --ignore-case --hidden --vimgrep'
" }}}

" Plugin: Rainbow {{{
let g:rainbow_active = 1
" }}}

" Plugin: vim-unimpaired {{{
" Bubble single line
nmap <C-Up> [e
nmap <C-Down> ]e

" Bubble multiple lines (visual mode)
vmap <C-Up> [egv
vmap <C-Down> ]egv
" }}}

" Plugin: Surround {{{
vmap ' S'
vmap " S"
" }}}

" Plugin: UltiSnips {{{
let g:UltiSnipsSnippetsDir=$HOME."/.vim/plugged/MyUltiSnips"
let g:UltiSnipsSnippetDirectories=[$HOME."/.vim/plugged/MyUltiSnips", "UltiSnips"]

autocmd FileType php UltiSnipsAddFiletypes php
" }}}

" vim:filetype=vim:foldmethod=marker:foldlevel=0
