#!/bin/bash

aws_sso_login() {
    if [ $# -eq 0 ]; then
        echo "Please provide an sso-session name"
        return 1
    fi

    aws sso login --sso-session "$1"
}

aws_sso_to_env() {
    if [ $# -eq 0 ]; then
        echo "Please provide a profile name"
        return 1
    fi

    if ! _aws_is_profile_logged_in "$1"; then
        echo "Profile '$1' is not logged in"
        return 1
    fi

    eval "$(aws configure export-credentials --profile "$1" --format env)"
}

_aws_list_profiles() {
    aws configure list-profiles 2>/dev/null
}

_aws_list_sso_sessions() {
    grep -oE '^\[sso-session [^]]+\]' ~/.aws/config | sed -E 's/^\[sso-session (.+)\]$/\1/'
}

_aws_is_profile_logged_in() {
    local profile="$1"
    aws sts get-caller-identity --profile "$profile" &>/dev/null
}

_fzf_complete_aws_sso_login() {
    _fzf_complete --reverse --prompt="aws sso-session> " -- "$@" <(_aws_list_sso_sessions)
}

_fzf_complete_aws_sso_to_env() {
    _fzf_complete --reverse --prompt="aws profile> " -- "$@" <(_aws_list_profiles)
}
