#!/bin/bash

aws_credentials_to_env() {
    if [ $# -eq 0 ]; then
        echo "Please provide a profile"
        return 1
    fi

    if ! aws configure list-profiles | grep -q "^$1\$"; then
        echo "No profile named \"$1\" found"
        return 1
    fi

    if ! aws sts get-caller-identity --profile "$1" >/dev/null 2>&1; then
        echo "Not logged in. Fetching profile credentials..."
        if ! aws sso login --profile "$1"; then
            echo "Failed to login"
            return 1
        fi
    else
        echo "Already logged in."
    fi

    echo "Setting credentials in shell..."

    cmd_output=$(aws configure export-credentials --profile "$1" --format env)
    while IFS= read -r line; do
        if echo "$line" | grep -q '^export [^=]\+=.*'; then
            # Strip leading "export " and split at '='
            var_name=$(printf "%s" "$line" | sed -E 's/^export ([^=]+)=.*/\1/')
            var_value=$(printf "%s" "$line" | sed -E 's/^export [^=]+=//')
            export "$var_name=$var_value"
        else
            echo "Error: Line doesn't match expected format: $line"
        fi
    done <<<"$cmd_output"

    echo "Done!"
}

_aws_list_profiles() {
    aws configure list-profiles 2>/dev/null
}

_aws_profiles_complete_zsh() {
    local profiles=()
    while IFS= read -r line; do
        profiles+=("$line")
    done < <(_aws_list_profiles)

    _describe 'aws profiles' profiles
}
