#!/bin/bash

# abbrev: cd file
cdf() {
    cd $(dirname "$@")
}

# abbrev: cd find
cdfi() {
    local search="$@"
    local file=$(find . -iname "$search" | fzf-tmux --no-multi -d 50%)

    if [[ -n $file ]]; then
        if [[ -d $file ]]; then
            cd "$file"
        else
            cdf "$file"
        fi
    fi
}

# abbrev: file which
fw() {
    local term="$@"
    file $(which "$term")
}
